name: BuildWin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-2025
    strategy:
      fail-fast: false # we want to see list of failing tests for each combination
      matrix:
        framework: [ "netstandard2.0" ]

    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Check out our repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: |
          dotnet build -f ${{ matrix.framework }} --exclude CloudNative.CloudEvents.AspNetCoreSample HttpSend
          dotnet test
          # Pack production packages to validate compatibility
          dotnet pack -p:ContinuousIntegrationBuild=true
